app:
  name: myservice
  log_level: info
  env: local

http:
  host: 0.0.0.0
  port: 8080
  read_timeout: 5s
  write_timeout: 10s

postgres:
  host: localhost
  port: 5432
  user: postgres
  password: postgres
  db_name: service-reviewer
  dsn: ""
  sslmode: disable
